name: lim2020
channels:
  - defaults
dependencies:
  - ipykernel
  - matplotlib=3.5.1
  - numpy=1.19.1
  - pandas=1.1.1
  - pip=24.0
  - python=3.8.5
  - pytest=7.4.4
  - pip:
    - pytest-xdist==3.6.1